cmake_minimum_required(VERSION 3.20)
project(PlumdeckRubberBand LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 20)
set(sources
 src/RubberBandStretcher.cpp src/RubberBandLiveShifter.cpp
 src/faster/AudioCurveCalculator.cpp src/faster/CompoundAudioCurve.cpp src/faster/HighFrequencyAudioCurve.cpp src/faster/SilentAudioCurve.cpp src/faster/PercussiveAudioCurve.cpp src/faster/R2Stretcher.cpp src/faster/StretcherChannelData.cpp src/faster/StretcherProcess.cpp
 src/common/Allocators.cpp src/common/FFT.cpp src/common/Log.cpp src/common/Profiler.cpp src/common/Resampler.cpp src/common/StretchCalculator.cpp src/common/sysutils.cpp src/common/mathmisc.cpp src/common/Thread.cpp src/finer/R3Stretcher.cpp src/finer/R3LiveShifter.cpp)
list(TRANSFORM sources PREPEND "${RB_SOURCE}/")
add_library(rubberband STATIC ${sources})
target_include_directories(rubberband PRIVATE "${RB_SOURCE}" "${RB_SOURCE}/src" "${RB_SOURCE}/rubberband")
find_path(SAMPLERATE_INCLUDE_DIR samplerate.h REQUIRED)
find_library(SAMPLERATE_LIBRARY NAMES samplerate REQUIRED)
target_include_directories(rubberband PRIVATE "${SAMPLERATE_INCLUDE_DIR}")
target_link_libraries(rubberband PUBLIC "${SAMPLERATE_LIBRARY}")
target_compile_definitions(rubberband PRIVATE HAVE_LIBSAMPLERATE MALLOC_IS_ALIGNED NO_THREAD_CHECKS NO_TIMING LACK_SINCOS)
if(APPLE)
  target_compile_options(rubberband PRIVATE -include cstddef)
  target_compile_definitions(rubberband PRIVATE HAVE_VDSP USE_PTHREADS)
  target_link_libraries(rubberband PUBLIC "-framework Accelerate")
elseif(MSVC)
  target_compile_options(rubberband PRIVATE /FIcstddef /utf-8)
  target_compile_definitions(rubberband PRIVATE USE_BUILTIN_FFT NOMINMAX _USE_MATH_DEFINES RUBBERBAND_STATIC)
else()
  target_compile_options(rubberband PRIVATE -include cstddef)
  target_compile_definitions(rubberband PRIVATE USE_BUILTIN_FFT USE_PTHREADS)
endif()
